### ISSUE TITLE
Add unit tests for all supported protocols (6 missing)

### ISSUE THREAD

**Issue by paul-pearce** [zmap/zdns#101]
The following protocols are advertised as supported, but have no unit tests:

* AXFR
* CNAME
* DMARC
* TXT
* SOA
* SPF 

We should also probably build out the framework so it tests iterative and non iterative queries without having to define the functions twice, once with `--iterative`

**Comment by paul-pearce** [comment]
I don't have control over the zdns test domain so I can't actually correct this issue. I'm willing to split the work with someone who does. (Note: Just giving me control over the test domain is probably not the right way to get me to do this. :P)

**Comment by dadrian** [comment]
What subdomains do you want?

**Comment by zakird** [comment]
I've created some new records:

old school SPF: "v=spf1 ?all"
new style SPF: "v=spf1 mx include:_spf.google.com -all"
_dmarc: "v=DMARC1; p=none; rua=mailto:postmaster@censys.io"
TXT: "test_txt.zdns-testing.com" -> "Hello World!"

**Comment by zakird** [comment]
SOA: `ns-cloud-e1.googledomains.com. dns-admin.google.com. 0 21600 3600 1209600 300`

**Comment by zakird** [comment]
- [ ] AXFR
- [x] CNAME
- [x] DMARC
- [x] TXT
- [ ] SOA
- [x] SPF
