### ISSUE TITLE
Add option to configure DNS class to query

### ISSUE THREAD

**Issue by stklcode** [zmap/zdns#102]
I recently had a setup where I had to query records in unusual classes, different from the default `INET` and therefore hardcoded the classes and built ZDNS with these changes.

Now I implemented an additional parameter `--class <CLASS>` which allows to specify the class beforehand. Possible values are `INET`, `CSNET`, `CHAOS`, `HESIOD`, `NONE`, `ANY` - defaults to `INET`. It obviously does not make sense in some combinations (maybe junk analysis), but it leaves the user all freedom for configuration.

This change does not introduce any overhead in the query itself. However to be consistent and do not loose any information (e.g. if `ANY` is queried), the class of both the query and the answer have been added to the resulting JSON, which increases the result size by 13 characters per record.

I'd like to see this addition in ZDNS, if it fits the scope.

**Comment by zakird** [comment]
Closing this since #103 is merged. Thank you for this PR. We were commenting this morning how this was one of the best documented and executed PRs we've seen in a while. :)
