### ISSUE TITLE
AXFR Tests

### ISSUE THREAD

**Issue by zakird** [zmap/zdns#107]
We don't have any tests for AXFR functionality currently.

**Comment by maaaaz** [comment]
In case it could be useful: 
* https://github.com/flotwig/TLDR-2
* https://github.com/flotwig/zone-walks
* https://github.com/monoidic/TLDR2

**Comment by phillip-stephens** [comment]
@zakird 
@vishalmohanty added this test about a year ago that makes an `AXFR` request for `zonetransfer.me` and verifies it returns as expected.
[integration test](https://github.com/zmap/zdns/blob/main/testing/integration_tests.py#L869)
[AXFR expected output](https://github.com/zmap/zdns/blob/main/testing/axfr.json)

IMO that brings AXFR up to the testing standard we have for other modules, if you agree feel free to close this!
