### ISSUE TITLE
(A/NS/MX)Lookup should never interact with the cache, instead use miekg abstraction

### ISSUE THREAD

**Issue by paul-pearce** [zmap/zdns#114]
Currently, cache operations at littered throughout the *lookups. This is not necessary, violates the abstractions, and makes trace not work properly. This should be replaced with cachedretryinglookup calls.

**Comment by phillip-stephens** [comment]
Further, let's be sure the cache is inaccessible from the outside, only handled internally. Should handle that one todo I have about what a comment was refereeing to about this.
