### ISSUE TITLE
Add `--detailed-timestamps` to add per-result before/after timestamps

### ISSUE THREAD

**Issue by paul-pearce** [zmap/zdns#123]
These will be omitempty fields in Result, that will also be empty except when we set the flag. We'll set these in cachedRetryingLookup based on the option.

**Comment by phillip-stephens** [comment]
This seems quite simple to add, wondering though if this is going to be only used to find the duration of resolution, would simply storing the elapsed time in milliseconds be more useful? I just can't think of a use of the real time of start/end of resolution besides calculating a duration. 

@zakird @paul-pearce tagging you to get your input here

**Comment by zakird** [comment]
I don't have a good sense of why high-resolution timestamps are useful here.

**Comment by phillip-stephens** [comment]
Alright, I'm going to close this then. @paul-pearce if you have any input feel free to re-open and add.
