### ISSUE TITLE
Handle to open the file number increasing, there is no decline, exceed the maximum limit of the operating system？

### ISSUE THREAD

**Issue by chushuai** [zmap/zdns#151]
I used the command line：
**cat   domains.cvs | ./zdns  a   --log-file="zdns.log"  --metadata-file="zdns_meta.log"  --timeout=25 --threads=1000 --output-file="zdns.cvs" --verbosity=1**
**[root@localhost tscan]# pgrep zdns
28114
[root@localhost tscan]# lsof -n|awk '{print $2}'|sort|uniq -c|sort -nr | grep \`pgrep zdns\`
  47608 28114**

znds open 47608 files,there is no decline

**Comment by zakird** [comment]
I suspect offhand this is due to sockets being opened. This can probably be limited by setting `--threads=x` lower and making sure that the kernel is cleaning up sockets quickly.

**Comment by mbudge** [comment]
ulimit -n 1000000 to temporarily change the limit
