### ISSUE TITLE
Recently introduced FTBFS: "undefined: dns.ErrTruncated"

### ISSUE THREAD

**Issue by d33tah** [zmap/zdns#155]
```
Step 36/36 : RUN go get github.com/zmap/zdns/zdns
 ---> Running in fcd3f160cf72
# github.com/zmap/zdns/modules/miekg
/home/nonroot/go/src/github.com/zmap/zdns/modules/miekg/miekg.go:509:12: undefined: dns.ErrTruncated
```

Probably a version of required package should be pinned or source updated.

**Comment by d33tah** [comment]
Most likely related: https://github.com/miekg/dns/commit/1ff265a78454967a4321dc2c0e38e267323bc3d4

**Comment by zakird** [comment]
It looks like this was fixed in the codebase a while back, so closing this issue.
