### ISSUE TITLE
Support CIDR notation for PTR module

### ISSUE THREAD

**Issue by mzpqnxow** [zmap/zdns#158]
Right now I need to write a tool to expand, e.g., 10.0.0.0/8 one IP at a time in a stream and pipe it to zdns PTR. It would be nice if I could just fire 10.0.0.0/8 to zdns PTR and have zdns expand the CIDR block for me. I feel this fits under the scope of zdns functionality as most tools support this and it is a relatively trivial change, I think. If I have time I will look at it and see if I can submit a PR but I haven't looked at the code for zdns and thus have no idea how difficult it will be to find the code that does this. If the project maintainer(s) can add this logic easily, that'd be swell too.

If the maintainers disagree this falls under the scope of zdns functionality, please comment here. Thank you.

**Comment by zakird** [comment]
I think this is probably out of scope as there are many linux utilities that could do this and we provide the `ziterate` tool that will expand CIDR blocks into a list of IPs that could be piped into ZDNS, e.g., `ziterate 10.0.0.0/8 | zdns ptr`
