### ISSUE TITLE
Add support for TLSA

### ISSUE THREAD

**Issue by seb-at-nzrs** [zmap/zdns#160]
Is it possible to add support to send TLSA queries (RFC 6698, https://tools.ietf.org/html/rfc6698)?

It could be great to discover the MX record for a bunch of domains and then follow up if there are TLSA records configured for them for a list of known ports.

**Comment by zakird** [comment]
We'd be happy to accept a pull request that adds support for TLSA queries.

**Comment by kesara** [comment]
PR: #161 adds support for TLSA and SRV.
