### ISSUE TITLE
TTL=0 does not get written to JSON output

### ISSUE THREAD

**Issue by pspacek** [zmap/zdns#165]
Example of broken domain:
```
$ dig jucesc.sc.gov.br NS

; <<>> DiG 9.14.4 <<>> jucesc.sc.gov.br NS
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 19089
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 5

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;jucesc.sc.gov.br.		IN	NS

;; ANSWER SECTION:
jucesc.sc.gov.br.	0	IN	NS	srvjucesc01.jucesc.sc.gov.br.
jucesc.sc.gov.br.	0	IN	NS	ns1.sc.gov.br.
jucesc.sc.gov.br.	0	IN	NS	srvjucesc02.jucesc.sc.gov.br.
```

Output from zdns:
```
        "answers": [
            {
                "type": "NS",
                "class": "IN",
                "name": "jucesc.sc.gov.br",
                "answer": "ns1.sc.gov.br"
            },
            {
                "type": "NS",
                "class": "IN",
                "name": "jucesc.sc.gov.br",
                "answer": "srvjucesc01.jucesc.sc.gov.br"
            },
            {
                "type": "NS",
                "class": "IN",
                "name": "jucesc.sc.gov.br",
                "answer": "srvjucesc02.jucesc.sc.gov.br"
            }
        ],
```

This is unexpected and requires special handling in JSON reader. It would be much easier to always write TTL value, even if it is zero.

Thank you for considering this.

**Comment by stklcode** [comment]
Problem is the struct definition of the `Answer` type:
https://github.com/zmap/zdns/blob/c4cc17aedca28e491b6756683063bcc0733ace42/modules/miekg/miekg.go#L21
`omitempty` on numeric values interprets zerso values as unset (as it cannot be distinguished from unset fields.

Zero is a valid value according to the [RFC](https://tools.ietf.org/html/rfc1035#section-3.2.1 "RFC 1035, sec 3.2.1")

Simply omitting the `omitempty` would return `ttl: 0` even if no TTL is contained in the answer section at all - for whatever reason this might be the case. Common solution would be turning the field into a pointer like
```go
Ttl     *uint32 `json:"ttl,omitempty"`
```
so the JSON marshaller is able to detect unset values (pointer with zero value) and print out zero values when set (pointer value != 0).

However if the TTL is really missing (i.e. the 4 octets of the RR header are skipped) parsing would lead to invalid results anyway, so not omitting zero-values here would be a legit solution.

----

Btw. the above example returns values of up to 3600 from my vantage point but nevermind I've found some other test candidates.
