### ISSUE TITLE
Add support for other record types (SRV, RRSIG, NAPTR, NSEC)

### ISSUE THREAD

**Issue by fbexiga** [zmap/zdns#179]
Add support for more record types
- SRV
- RRSIG
- NAPTR
- NSEC

**Comment by stklcode** [comment]
`SRV` AND `NAPTR` are already supported. 
Just enter `zdns` without any arguments to see the full list. ReadMe is not complete.

Supported:
NSEC3PARAM, **NAPTR**, NSLOOKUP, AAAA, CDS, MXLOOKUP, NS, DNSKEY, MX, DS, DMARC, A, SOA, AXFR, CAA, SPF, TXT, TLSA, **SRV**, CDNSKEY, PTR, ALOOKUP, ANY, CNAME

**Comment by fbexiga** [comment]
I was using the version available from "go get". I should build from master then, right?

**Comment by zakird** [comment]
go get should get what's in master.

**Comment by fbexiga** [comment]
Yep you are right. Noob me was using older version and forgot the -u. Still, is there a particular reason why only NSEC3PARAM was implemented and not NSEC3 or NSEC?

**Comment by zakird** [comment]
No good reason. Someone just needs to implement it and it hadn't come up.
Happy to merge a PR that adds it.

**Comment by fbexiga** [comment]
@zakird https://github.com/zmap/zdns/pull/180

**Comment by zakird** [comment]
Thank you! I've merged the PR, which looks like it provides coverage over the remaining types, so I'm going to go ahead and close this. Thanks again for adding the support.

**Comment by fbexiga** [comment]
No problem. Thank you for the awesome tool and for making it so easy to add the new types.
