### ISSUE TITLE
Add option which passes resolvers using file

### ISSUE THREAD

**Issue by wavvs** [zmap/zdns#185]
Currently if I want to pass 1000 resolvers I need to pass string in -name-servers option, which is not convenient at all. Please, add such an option.

**Comment by zakird** [comment]
We'd be happy to accept a pull request that adds this feature if you can
submit one.

**Comment by stklcode** [comment]
Wondering which implementation would be more convenient. Additional parameter like `--name-servers-file` or @-syntax like `--name-servers @/path/to/file`

**Comment by zakird** [comment]
#187 resolves this issue, so closing.
