### ISSUE TITLE
Problem building zdns

### ISSUE THREAD

**Issue by Cyb0rg42** [zmap/zdns#207]
I'm trying to build zdns on Ubuntu 18.04.4 and get the following error:
$ git clone https://github.com/zmap/zdns.git
$ cd zdns
$ make
cd zdns && go build
# github.com/zmap/zdns/modules/miekg
/home/karl/go/src/github.com/zmap/zdns/modules/miekg/miekg.go:279:12: s.Client.LocalAddr undefined (type *dns.Client has no field or method LocalAddr)
/home/karl/go/src/github.com/zmap/zdns/modules/miekg/miekg.go:292:12: s.Client.LocalAddr undefined (type *dns.Client has no field or method LocalAddr)
makefile:4: recipe for target 'zdns/zdns' failed
make: *** [zdns/zdns] Error 

Any idea to to fix this problem?

Cheers,
Karl

**Comment by stklcode** [comment]
Which verison of _Go_ are you using?

Most likely you're building without Go Modules support, i.e. _go.mod_ or at least the _replace_ statement is ignored and you're building against the wrong DNS library. (related to #205)

Go should be 1.11 or above. Makefile runs fine inside `golang:1.11` - `golang:1.14` Docker containers.

**Comment by Cyb0rg42** [comment]
Thanks. Added the go repo and updated to 1.14. Ubuntu 18.04.4 has 1.10

$ sudo add-apt-repository ppa:longsleep/golang-backports
$ sudo apt update
$ sudo apt install golang-go

Thanks.....

**Comment by umbrellarfrank** [comment]
Hi, I'm having the same problem on Ubuntu 18.04. Using go1.14 linux/amd64 from the golang-backports repo as above.

**Comment by mischief13** [comment]
Hi - I'm having a similar issue installing on mac (not using docker). I'm using go version go1.14.2 darwin/amd64

It looks like the same error here and in #205 

$ go get github.com/zmap/zdns/zdns

go/src/github.com/zmap/zdns/modules/miekg/miekg.go:279:12: s.Client.LocalAddr undefined (type *dns.Client has no field or method LocalAddr)

I looked at this issue and #205 but it's still not clear to me how to get it to work esp with getting it to use go.mod with the right version of zmap/dns and what it means to fix:

"That error arises from using an older version of zmap/dns than is specified in go.mod."

I'm not that familiar with Go so appreciate any help on troubleshooting this.

Thanks,
Crystal

**Comment by zakird** [comment]
Your best bet is going to be:
```
git checkout https://github.com/zmap/zdns.git
cd zdns
go build
```
