### ISSUE TITLE
Generalize Input/Output handlers to io.Reader, io.Writer

### ISSUE THREAD

**Issue by jcrowgey** [zmap/zdns#209]
I'm using zdns in a larger context (importing it) and it's inconvenient to require file paths when in-memory byte-streams will do.  Looking at the exsting iohandlers/ (ie, the implementations of InputHandler and OutputHandler interfaces), there's only the "file" version, which requires a path on disk (or "-" as a stand-in).   After opening the file, these handlers generally uses library functions that are abstracted to require io.Reader/io.Writer anyway (eg, calls to bufio.NewScanner, or WriteString).

To solve my issue (which is that my data isn't necessarily in a file on disk), I've got a couple of paths forward: I can create my own Input/Output handlers for "stream" which will basically just require the io.Reader io.Writer types to be passed to them.  If I go that route and that would be useful for others, I'm happy to offer a PR with those implementations change.  Alternatively, I can modify the existing "file" handlers so that they're generalized to io.Reader, io.Writer and modify znds/main.go to do the open/close based on what's been asked for by the user.

Effectively, it seems like the library/package aspects of zdns shouldn't really care whether the input/output is a file or not, and it's not clear to me that we need separate implementations of the InputHandler/OutputHandler interfaces in order to support library users vs command line users.  That's because the command-line users are just the same as the library users after a call to os.Open.  And the command-line app can handle that call before init'ing the factory.

Any thoughts or suggestions?

**Comment by dadrian** [comment]
We'd be happy to take a PR that exposes stream-based handlers and defers the open/close to main.
