### ISSUE TITLE
Inconsistent json output

### ISSUE THREAD

**Issue by umbrellarfrank** [zmap/zdns#214]
When performing a large number of MX lookups (35838) in this case, the resulting json file output appears in a completely inconsistent/incomplete json object:

For example the following snippet:
```
{
	"data": {
		"exchanges": [{
			"class": "IN",
			"ipv4_addresses": ["1.2.3.4"],
			"name": "redacted.net",
			"preference": 5,
			"ttl": 472,
			"type": "MX"
		}]
	},
	"name": "redacted.com",
	"status": "NOERROR",
	"timestamp": "2020-04-22T12:58:24+12:00"
} {
```
Results in:
```
Error: Parse error on line 15:
...2T12:58:24+12:00"} {	"data": {		"exch
----------------------^
Expecting 'EOF', '}', ',', ']', got '{'
```

**Comment by zakird** [comment]
can you provide a copy of the command you're running? ZDNS shouldn't ever be outputting a json record split across multiple lines.

**Comment by umbrellarfrank** [comment]
``root@ubuntu:/home/ubuntu# zdns mxlookup --ipv4-lookup -input-file test.txt -output-file test.json.txt
 -name-servers=1.1.1.1 --threads=1 -go-processes=1 -timeout 90 -tcp-only``

Files attached.

[test.json.txt](https://github.com/zmap/zdns/files/4513635/test.json.txt)
[test.txt](https://github.com/zmap/zdns/files/4513636/test.txt)

**Comment by zakird** [comment]
I don’t think I’m seeing the issue. This output looks sane. Can you describe what you’re expecting?

**Comment by fujin** [comment]
Hi @zakird, helping @paragenicx remotely via IRC. 

From what I can see, the difference in expectation came from expecting a JSON stream (e.g. an array of objects), vs. expecting "JSON-formatted logs" type output (one object separated by linefeed). I advised @paragenicx to try piping output (or reading input) into `jq --slurp .` to enable further indexing/filtering or transformation.

In my opinion, an "JSON file output" might be expected to write a single valid JSON object (likely an array of objects in this case).

Perhaps the output formatter could be described explicitly as JSON-formatted logs (Result objects separated by linefeed) :thought_balloon:

**Comment by zakird** [comment]
Gotcha. Yeah, the output is in [JSON Lines](http://jsonlines.org/). jq should handle this natively.

**Comment by zakird** [comment]
Closing since the issue was that jsoslines format was unexpected.
