### ISSUE TITLE
dns: id mismatch on big scans

### ISSUE THREAD

**Issue by jcrowgey** [zmap/zdns#215]
When doing very large numbers of lookups, I get as many as 10% ERROR where the error is "dns: id mismatch".  As I increase the number of goroutines, I can decrease the proportion of these errors.

I'm relatively certain that the root of the issue is that a reply came back very late, in such a way that the goroutine managing that Conn has moved on to the next lookup.  The miekg client sends a message and then happens to receive a reply from a previous message, and thus generates the id-mismatch error.

Interstingly (to me), I find that increasing the timeout value didn't really affect the count of these errors.  I haven't yet fully digested the entire codebase in order to see if there's some other parameter I might adjust in order to alleviate this.  I'd love suggestions about how to tune zdns to minimize this.

**Comment by zakird** [comment]
Fascinating, I don't think we've run into that error. Are you running in `--iterative` mode or hitting an upstream recursive resolver. IF there's an upstream resolver, do you know what DNS stack it's running?

**Comment by jcrowgey** [comment]
This was with without iterative, with upstream pointed at cloudflare (1111, 1001).   You should be able to repro this (I would suppose) by taking 50K DNS names and running with about 8K -threads.  When I do that on a laptop on a residential IP, I see about 4 - 10 of these mismatches.  If I run 500K names with ulimit nofiles at like 32K and threads = 16K on an AWS node, I can get as many as 50K of these id mismatches

**Comment by theloglizard** [comment]
You might do well to run some traceroutes to Cloudflare in AWS, looking for a gateway proxy.

Running in GCP,  I have a gateway proxy between my zdns host and the Internet. The proxy causes all kinds of problems, and in the case of zdns, I suspect the proxy only allows me to have a certain number of open sockets -- effectively limiting my thread count. At least it seems to behave that way. Depending the circumstances zdns on my cheesy little home router gives me better throughput when using a lot of threads.
