### ISSUE TITLE
dns.ParseZone function no longer present in miekg/dns

### ISSUE THREAD

**Issue by tarexveff** [zmap/zdns#218]
I suspect dns.Token is also missing now too (see commit: https://github.com/miekg/dns/commit/d128d10d176b810543f8fecd089082a29d3f159d)

Errors encountered during zdns build:
 
go/src/github.com/zmap/zdns/iohandlers/filehandlers.go:37:13: undefined: dns.ParseZone
go/src/github.com/zmap/zdns/iohandlers/streamhandlers.go:27:13: undefined: dns.ParseZone
github.com/zmap/zdns
go/src/github.com/zmap/zdns/interface.go:51:27: undefined: dns.Token
go/src/github.com/zmap/zdns/interface.go:62:50: undefined: dns.Token
go/src/github.com/zmap/zdns/lookup.go:99:33: undefined: dns.Token
go/src/github.com/zmap/zdns/lookup.go:103:30: undefined: dns.Token
go/src/github.com/zmap/zdns/lookup.go:105:33: undefined: dns.Token
go/src/github.com/zmap/zdns/lookup.go:110:62: undefined: dns.Token

**Comment by zakird** [comment]
This shouldn't be an issue if you're building ZDNS using the following:
```
git checkout https://github.com/zmap/zdns.git
cd zdns
go build
```

since we replace miekg's DNS with a forked version at https://github.com/zmap/dns. We clearly need to document this. That said, we'll pull upstream changes at some point and then things will break.

**Comment by tarexveff** [comment]
Ah, thank you, I'll try building by that method instead.  Thanks much!

**Comment by tarexveff** [comment]
That worked!  Thank you much, and for updating the documentation already.  Have a great weekend!
