### ISSUE TITLE
unable to create socketlisten udp

### ISSUE THREAD

**Issue by scanpatch** [zmap/zdns#219]
Hello and thank you for an awesome project!

I get an error when starting more than ~10,000 threads. Command example:

```
cat alexa-1m.yml | ./bin/zdns A -threads 50000 -timeout 7
```
Output with error:
![image](https://user-images.githubusercontent.com/3992998/81973707-2b28a480-962d-11ea-87b3-75f4e7d692c3.png)

Should I increment ulimits or do other implicit actions to work with so many threads?

**Comment by zakird** [comment]
Upping ulimit won't actually fix this. If you got to that error, then you already had permission to try to open the socket. First, make sure you've built ZDNS like this:
```
git checkout https://github.com/zmap/zdns.git
cd zdns
go build
```

Which makes sure you're using our forked version of miekg's DNS library that is _significantly_ more efficient and doesn't create a ton of unnecessary sockets. 

If you are, and that doesn't work, your next option is to run ZDNS with multiple source IP addresses.

**Comment by DarkMristov** [comment]
Hello. same problem.

Can you please specify how can i run ZDNS  with multiple source IP addresses?
I am tried to use` -local-addr 127.0.0.1,127.0.0.2,127.0.0.3` and got all records with error like this:
`write udp 127.0.0.1:60801-\u003e178.15.146.43:53: sendto: invalid argument`

Assuming that i am doing wrong thing i tried to use another IP in my local network 
`-local-addr 192.168.9.252,192.168.9.253`

But get another error:
`unable to create socketlisten udp 192.168.9.253:0: bind: cannot assign requested address`

Looks like this problem show up after i updated ZDNS to last commit.
Before that i am used commit `6d2d6ea7261929a3f19580da613a029a180df8ef.`

**Comment by DarkMristov** [comment]
Upd.
I am dig out my old bin builded on commit `6d2d6ea7261929a3f19580da613a029a180df8ef`, and looks like it work without problem.

So i am checkout on commit `6d2d6ea7261929a3f19580da613a029a180df8ef` to build zdns, but looks like there is not go.mod, so i am use go.mod from last commit. 
Same problem.

And i am tried to build zdns with older version of `github.com/zmap/dns`.
Same problem.

And same problem with `github.com/miekg/dns`.

Maybe i am doing it wrong, but i cant figure out what can i do else ...

**Comment by DarkMristov** [comment]
Upd.
I am switch to go 1.13 and checkout to commit `6d2d6ea7261929a3f19580da613a029a180df8ef`.
Then i am create go.mod:
```
module github.com/zmap/zdns

go 1.13

require (
	github.com/asergeyev/nradix v0.0.0-20170505151046-3872ab85bb56 // indirect
	github.com/hashicorp/go-version v1.2.0
	github.com/kavu/go_reuseport v1.4.0 // indirect
	github.com/liip/sheriff v0.0.0-20190308094614-91aa83a45a3d
	github.com/miekg/dns v1.1.27
	github.com/sirupsen/logrus v1.4.2
	github.com/zmap/go-iptree v0.0.0-20170831022036-1948b1097e25
	golang.org/x/crypto v0.0.0-20200117160349-530e935923ad // indirect
	golang.org/x/net v0.0.0-20200114155413-6afb5195e5aa // indirect
)
```

Without:
`replace github.com/miekg/dns => github.com/zmap/dns v1.1.28-zmap-3`

And looks like no problem here.

So i am back to last commit, remove from go.mod that string:
`replace github.com/miekg/dns => github.com/zmap/dns v1.1.28-zmap-3`
But got build error:
`modules/miekg/miekg.go:279:12: s.Client.LocalAddr undefined (type *dns.Client has no field or method LocalAddr)
modules/miekg/miekg.go:292:12: s.Client.LocalAddr undefined (type *dns.Client has no field or method LocalAddr)
`
@zakird help, pls.

**Comment by gy741** [comment]
Hello,

I get the error as below.

```
unable to create socketlisten udp socket: too many open files
```

Thanks.

**Comment by zakird** [comment]
This is a ulimit issue. You need to increase the number of sockets you can open.

**Comment by gy741** [comment]
Hello, @zakird  Using the command "ulimit -n 999999" also results in an error.

The first few seconds are fine. There is an error over time.

**Comment by zakird** [comment]
You need to work out why that's erroring. That's a system issue, not a ZDNS issue.

**Comment by scanpatch** [comment]
@zakird

In my case, ZDNS was build in the right way.
Same as @DarkMristov i cannot understand how to provide multiple source IP addresses. Problems are the same https://github.com/zmap/zdns/issues/219#issuecomment-637441023

I asked my colleagues to check the new version of ZDNS, and all of them have the same problem in very different environments.  

Previous versions of ZDNS worked well, but now there is no way to roll back to them :(

**Comment by zakird** [comment]
You need to have real multiple real public IPs, not localhost addresses. Otherwise, just use fewer source ports ~10K or increase the Linux ephemeral port space you have available.

**Comment by halilemreozen** [comment]
> Hello, @zakird Using the command "ulimit -n 999999" also results in an error.
> 
> The first few seconds are fine. There is an error over time.

For people who came here after facing this error message.
I got this error when I tried my CSV file ( 200000 domain ) and after using "ulimit -n 999999" it's successfully complete the job.
