### ISSUE TITLE
Set DO flag when doing NSEC lookups.

### ISSUE THREAD

**Issue by simonvik** [zmap/zdns#220]
Some DNS servers wont answer on NSEC querys unless the DO flag has been set.

Easiest patch is to add `	m.SetEdns0(1232, true)` in `DoLookupWorker` but i dont know if its desired to do this on all querys. 

Perhaps some flag is needed for EDNS buffer size and DO?

**Comment by zakird** [comment]
I think that’s probably fine to set globally for now. Can you submit PR?

**Comment by zakird** [comment]
Addressed by #323
