### ISSUE TITLE
CNAME of NXDOMAINs

### ISSUE THREAD

**Issue by sw33tLie** [zmap/zdns#223]
Hello,
I've recently switched from massdns to zdns and it's great!
I only have one problem, though.
With massdns I was able to get the CNAMEs for NXDOMAINs, which was useful to detect subdomain takeovers...is there a way to do the same with zdns? 
Thank you

**Comment by sw33tLie** [comment]
![image](https://user-images.githubusercontent.com/47645560/83326570-5807c900-a275-11ea-8753-ffd32cbd4215.png)
Here's an example

**Comment by zakird** [comment]
Does this happen if you use the `CNAME` module? I'm guessing that you're seeing this problem with `ALOOKUP`?

**Comment by sw33tLie** [comment]
You are right, that works just fine...sorry for opening this silly issue.
Thanks again, have a nice day :)
