### ISSUE TITLE
question with iterative mode

### ISSUE THREAD

**Issue by dialectically** [zmap/zdns#229]
Hi, Sir.

I did a test with
```echo "www.github.com" | zdns A --iterative```

And I found that the process is this.
root dns servers(gtld-servers in fact) return github's dns server address, then the local send a lookup to github's dns server. what's the difference between this and send dns lookup to github's dns servers directly? And why this can prevent from being banned/limited from dns servers when resolving a huge of subdomains?
![image](https://user-images.githubusercontent.com/50006201/86604626-34544300-bfd8-11ea-9126-1ce5d654189b.png)

**Comment by zakird** [comment]
You wouldn't know the IP address of Github's DNS server otherwise.
