### ISSUE TITLE
list of resolvers?

### ISSUE THREAD

**Issue by marcelo321** [zmap/zdns#233]
Hello

Maybe I am missing something, but isn't there an option to provide a list of resolvers instead of writting them one by one with the --name-servers flag?

**Comment by wavvs** [comment]
> Hello
> 
> Maybe I am missing something, but isn't there an option to provide a list of resolvers instead of writting them one by one with the --name-servers flag?

You can provide file using `--name-servers=@/path/to/file` syntax.

**Comment by marcelo321** [comment]
Hey @zakird @wavvs @stklcode,

Neither `--name-servers=@/path/to/file` or `--conf-file` is working.

When trying `--conf-file listofresolvers` I get the error that says no name servers provided.

When trying `--name-servers=@/path/to/file` I got everything as SERVFAIL, the same output as when I don't select dns resolvers with the other flag.

**Comment by marcelo321** [comment]
OH YEAH IT WORKS, THANK YOU --name-servers=@file

**Comment by djinnnn** [comment]
can i offer resolvers's ip as format with prefix, like this 10.0.0.0/8?
