### ISSUE TITLE
Add support for SVCB and HTTPS resource record queries

### ISSUE THREAD

**Issue by chris-wood** [zmap/zdns#236]
[miekg/dns recently added SVCB/HTTPS support](https://github.com/miekg/dns/pull/1067). Adding query support to zdns would be great. If folks generally agree, I can submit a PR to add it. (That would require updating the zmap fork of miekg/dns, but that doesn't seem terribly complicated.)

**Comment by zakird** [comment]
Sounds good to me.

**Comment by chris-wood** [comment]
@zakird I'll send some PRs, then. Thanks!

**Comment by zakird** [comment]
Everything is in place to do this in ZDNS now (this happened last week, but I forgot to update this issue, sorry about that)

**Comment by happywhitelake** [comment]
Thanks @chris-wood ❤️
This would be great! Looking forward to the addition of these two new rr types.

**Comment by constantinsander** [comment]
I added a PR for this issue, I hope that's okay @chris-wood :)

**Comment by chris-wood** [comment]
Yes, definitely! Thank you for doing the work. :-)
