### ISSUE TITLE
Prefix in DMARC module differs from RFC

### ISSUE THREAD

**Issue by bayerhonza** [zmap/zdns#252]
Hello,

while using the DMARC module, we found that its implementation [modules/dmarc/dmarc.go#L56](https://github.com/zmap/zdns/blob/ed5b6828b56753f42903a3b7b82ade161e65ec02/modules/dmarc/dmarc.go#L56) checks only the first 7 characters ("v=DMARC") of DMARC TXT record and not the ABNF defined in [RFC 7489](https://datatracker.ietf.org/doc/html/rfc7489) as "v=DMARC1" with optional whitespaces.

This can lead to cases when a DMARC of a domain is not set up correctly (e.g. "v=DMARCv1") and zdns' result status is "NOERROR" even though the DMARC configuration is not valid.

Is it an intentional behviour?

Thanks.

**Comment by zakird** [comment]
This sounds like a bug. Would you be willing to submit a pull request to
fix?

**Comment by bayerhonza** [comment]
Sure, I will submit the request ASAP.
