### ISSUE TITLE
SPF prefix should be case insensitive

### ISSUE THREAD

**Issue by bayerhonza** [zmap/zdns#253]
[RFC 7208](https://datatracker.ietf.org/doc/html/rfc7208) notes that literal text strings in ABNF are case-insensitive.

This means that following SPF records are valid but do not apear as valid records while using zdns with SPF module:

| SPF record | zdns result|
| -------- | ----------------|
| v=spf1 | NOERROR |
| V=sPf1 | **NORECORD** |
| v=SPF1 | **NORECORD** |

Checking the SPF prefix ("v=spf1") should be case-insensitive in order to conform to RFC.

**Comment by zakird** [comment]
Thanks! Would you be willing to submit a PR to address this?

**Comment by bayerhonza** [comment]
Yes, I will submit a PR together with #252

**Comment by zakird** [comment]
Fantastic, thank you!!
