### ISSUE TITLE
Request for (and failure to implement!) "PTR" lookup module

### ISSUE THREAD

**Issue by brandonpoc** [zmap/zdns#28]
I was surprised to see there is no "PTR" module for doing quick PTR lookups on IPs. There's DMARC lookups(!) but no PTR. Would anyone implement this? I ask because I failed implementing it - read below...

I know absolutely nothing about the "Go" language, but being a C programmer I thought I'd take a stab at implementing a PTR module as we have a need to do PTR lookups with the speed and ability of zdns. I thought it'd be as easy as copying one of the existing modules, such as "A" (modules/a/a.go), renaming it to ptr, renaming the module registration from "A" to "PTR", changing the lookup type to TypePTR and formatting the request properly as reverse-IP.in-addr.arpa. The request goes out, and sniffed via tcpdump I can see that the request is sent properly and the response is correct BUT the output is not correct: (from zdns, below, using my "PTR" module that is implemented exactly as detailed above)

8.8.8.8
{"name":"8.8.8.8","status":"success","data":{"answers":[],"additionals":[],"authorities":[],"protocol":"udp"}}

I can show you the code but its exactly as I described - just a copy of "modules/a/a.go" with the name of the package changed, the hook to register the module changed from "A" to "PTR", and a quick strings.Split() of the IP to construct a "in-addr.arpa" request to send off to the chosen random nameserver.

So - do I need to implement some extra code to handle the response? I thought with the "TypePTR" and PTR requests being implemented in the DNS library that the response would be handled properly. Again I know nothing about Go, and I can't really make sense of what is going on with the code over-all...

Thanks in advance!

**Comment by zakird** [comment]
This should be resolved by #29. Please try and let me know if it seems to work for you.

**Comment by brandonpoc** [comment]
I am getting the following error when I run with PTR module - 

panic: runtime error: slice bounds out of range

You have this:

```
    name, err := dns.ReverseAddr(name)
    if err != nil {
            log.Fatal("Invalid IP address received:", name)
    }
    name, _ = dns.ReverseAddr(name)
```

ReverseAddr is being called twice - I removed the second call, and all works fine (as seen below). Just remove line #38 in modules/ptr/ptr.go and it's fixed. Otherwise it's borked. See working output below with line #38 removed:

{"name":"8.8.8.8","status":"success","data":{"answers":[{"ttl":58540,"type":"PTR","name":"8.8.8.8.in-addr.arpa","data":"google-public-dns-a.google.com."}],"additionals":[],"authorities":[],"protocol":"udp"}}

Thank you!

Brandon

**Comment by zakird** [comment]
Whoops! Sorry about that. This should be fixed in master.

**Comment by zakird** [comment]
I'm going to close this as our testing finds that this currently works. If this is not the case, please don't hesitate to reopen.
