### ISSUE TITLE
Add a prompt when zdns is running

### ISSUE THREAD

**Issue by vishalmohanty** [zmap/zdns#288]
Currently when zdns is running, there is no indication that we are expecting input. 
```
vishalmohanty@DN51t4bg:~/Documents/Stanford/Acads/zdns/vishalmohanty/zdns(validateInput⚡) » ./zdns axfr

```
Add a prompt like
```
vishalmohanty@DN51t4bg:~/Documents/Stanford/Acads/zdns/vishalmohanty/zdns(validateInput⚡) » ./zdns axfr
>>>
```

**Comment by zakird** [comment]
I don't think this necessarily makes sense. No other command line tools that take input, from `grep` and `awk` to `zgrab` provide this.
