### ISSUE TITLE
Import case-sensitivity with github.com/Sirupsen/logrus

### ISSUE THREAD

**Issue by PenelopeFudd** [zmap/zdns#295]
Small problem with `go install github.com/zmap/zdns@latest`:
```
$ sudo bash
# wget https://go.dev/dl/go1.18.linux-amd64.tar.gz
# tar -C /usr/local -xzf go1.18.linux-amd64.tar.gz
# vi ~/.bashrc  ## fix up path to include /usr/local/go/bin
# source ~/.bashrc
# go install github.com/zmap/zdns@latest
 
go: downloading github.com/zmap/zdns v1.0.0-RC1
go: finding module for package github.com/miekg/dns
go: finding module for package github.com/Sirupsen/logrus
go: downloading github.com/miekg/dns v1.1.47
go: downloading github.com/Sirupsen/logrus v1.8.1
go: found github.com/Sirupsen/logrus in github.com/Sirupsen/logrus v1.8.1
go: found github.com/miekg/dns in github.com/miekg/dns v1.1.47
go: github.com/zmap/zdns imports
	github.com/Sirupsen/logrus: github.com/Sirupsen/logrus@v1.8.1: parsing go.mod:
	module declares its path as: github.com/sirupsen/logrus
	        but was required as: github.com/Sirupsen/logrus
```

**Comment by zakird** [comment]
I would install from master. ZDNS isn't well versioned today and v1.0 is very old (like... 6 years old). I believe this bug in particular was fixed at some point in the 2010s . We're working on fixing up some framework pieces this quarter and then are going to start releasing semantic versioned releases.

**Comment by PenelopeFudd** [comment]
I did go on to install from master, so I'm able to run zdns and get on with my work.

This issue was created because the [README.md](https://github.com/zmap/zdns/blob/master/README.md) file in master (i.e. the instructions shown at https://github.com/zmap/zdns) shows `go install github.com/zmap/zdns@latest` as the first of two methods for installing zdns, and as we've seen, it doesn't work.  😕 

It seems that `go install github.com/zmap/zdns@latest` sees that `v1.0.0-RC1` is the latest tag (it's the only tag), so perhaps the thing that needs to be done is the creation of a newer tag?

Alternatively, delete `go install github.com/zmap/zdns@latest` from the list of installation methods (until it works again).  😃 

Thanks for a great program!

**Comment by zakird** [comment]
I'll update README — thanks for calling out. We'll create a new tag once we're in a place to semantically version appropriately.
