### ISSUE TITLE
GOMAXPROCS flag unncessary

### ISSUE THREAD

**Issue by dadrian** [zmap/zdns#3]
GOMAXPROCS now defaults to the number of processor cores on the system. This is the default we would want anyway, and it can still be overrided  using the `$GOMAXPROCS` environment variable.

**Comment by zakird** [comment]
Given that explicitly call all these things as part of a framework, where everything is defined as command line flags, I'm not sure that this change makes sense.

**Comment by zakird** [comment]
I'd be OK with checking if it's in the environment and erroring if you also
pass it in? As is though, seems like there's no harm and it fits in much
better with our existing infrastructure.

**Comment by dadrian** [comment]
Maybe we should default to `-1` or `0`, and use that as a sentinel to mean "don't set `runtime.GOMAXPROCS`?

**Comment by zakird** [comment]
sounds good to me.
