### ISSUE TITLE
Lookup via IPv6 nameservers

### ISSUE THREAD

**Issue by vishalmohanty** [zmap/zdns#304]
What is the right way to lookup via IPv6 nameservers? Once this is figured out, add the functionality to `all-nameservers` mode so that we can lookup via both IPv4 and IPv6 nameservers.

**Comment by mutax** [comment]
When I was looking through the code it seems to me that no attempt is made to resolve the IPv6 adresses of NS records, so IPv6 is currently not supported when recursing locally.

**Comment by paul-pearce** [comment]
@vishalmohanty @mutax I'm working on this on the fix-ipv6 branch. I have initial support committed. It appears functional but I haven't had time to fully test it yet. Please let me know what you think. zdns should now:

* Properly detect and classify v6 nameservers
* Properly detect and classify v6 local addresses (and ignore link-local)
* Based on the nameserver it's trying to connect too, utilize either established v4 and v6 state (if configured)

There's a bug where if you try to force zdns into a bad state (e.g., force bind to v4 but force v6 nameservers) it will error, which I will fix shortly.

**Comment by zakird** [comment]
@paul-pearce, can you put this code in a branch? I'd like to have @phillip-stephens take a look at getting this fixed this fall.

**Comment by phillip-stephens** [comment]
@zakird Just want to confirm, should I be ignoring all link-local nameservers for IPv6? Was unsure why that'd be different from IPv4.

**Comment by zakird** [comment]
I think that makes sense

**Comment by phillip-stephens** [comment]
Closed with merging in IPv6 support in #410
