### ISSUE TITLE
A list of cloud providers ok with running zdns?

### ISSUE THREAD

**Issue by alexey-milovidov** [zmap/zdns#314]
We have a task to do reverse lookups of all IPv4 space, and when it is done, repeat it in an infinite loop. Leave it run for years.
Are there cloud providers who are known to don't mind this operation?

**Comment by xiaopihaiK** [comment]
Do you check the domain name by IP?

**Comment by alexey-milovidov** [comment]
Yes, PTR lookups.

**Comment by xiaopihaiK** [comment]
Can i add your telegram？

On 周一, 9月 19, 2022 18:08, Alexey Milovidov ***@***.***> 来信：

**Comment by zakird** [comment]
I would use Cloudflare (e.g., 1.1.1.1) and/or Google (e.g., 8.8.8.8). We have some details here about their performance (https://zakird.com/papers/zdns.pdf), but both providers are pretty good. You can also use `--iterative` if you don't want to depend on any external providers. I would not use the default Amazon or other cloud providers. Given past experiences, I would expect better network performance for this type of task on Amazon compared to Google. 

CARI.net is generally pretty open to network measurement as well if you reach out to their support team.
