### ISSUE TITLE
ALOOKUP Module does not follow CNAMEs consistently

### ISSUE THREAD

**Issue by zakird** [zmap/zdns#33]
It appears that the ALOOKUP module doesn't always provide back any data if there's a cname present. For example, `www.censys.io`:

echo "www.censys.io" | ./zdns alookup
INFO[0000] no name servers specified. will use: 172.19.134.2:53 
{"name":"www.censys.io","status":"success","data":{}}

**Comment by bvandersloot** [comment]
#35
