### ISSUE TITLE
Support for DoH lookups

### ISSUE THREAD

**Issue by tillson** [zmap/zdns#336]
One issue I've run into when using zdns is that sometimes, the network firewall intercepts and rewrites DNS lookups (in my case, due to the domain being blocklisted). I don't have the ability to turn this off, so it would be useful if we could circumvent this firewall by leveraging DoH to do mass lookups.

I'd be interested in helping out with the implementation of this but am first wondering whether you all, as the primary maintainers, think that this is in-scope and useful for the zdns project, or if it would be better suited for a different project like zgrab.

Thanks

**Comment by zakird** [comment]
Absolutely open to it!! We've been wanting to see this for a long time, but just haven't had the time to do it.

**Comment by cinado** [comment]
I'm interested in implementing DoH support for ZDNS. Are there any specific considerations I should keep in mind during the implementation?

**Comment by phillip-stephens** [comment]
Note:  only applicable for external lookups
