### ISSUE TITLE
Perform multiple queries in the same run

### ISSUE THREAD

**Issue by maaaaz** [zmap/zdns#353]
Hello there,

Thanks for this great tool!

If I am not wrong, it is currently impossible to perform, in a same run/execution, different DNS query types: that is to say, we can't say "perform an A query _and_ an AAAA query". So we need to perform X runs for X different records.

Would it be possible to have an option allowing us to perform multiple, at least two (A and AAAA), queries in a same run ?

Cheers!

**Comment by phillip-stephens** [comment]
This should definitely be possible, and seems reasonable to me. Using this from the CLI could be something like:
`echo "google.com" | ./zdns A AAAA`.

We'll just need to be sure the output allows a consuming program/user to disambiguate what query a result is in reference to. That looks to be the case for the basic DNS record types (`A` and `AAAA` but not the modules that do more complicated querying - `ALOOKUP`, etc.)

I'll take this on.

**Comment by zakird** [comment]
Addressed by #429.
