### ISSUE TITLE
Improve Documentation for Input List Format

### ISSUE THREAD

**Issue by developStorm** [zmap/zdns#355]

**Comment by phillip-stephens** [comment]
This is a good issue, we should document all the various ways you pass input to ZDNS. A non-exhaustive list:
 - Single Domain: `echo "censys.io" | ./zdns A`
 - Single Domain with Name Server: `echo "censys.io,1.1.1.1" | ./zdns A`
 - Multiple Domains: `cat domains.txt | ./zdns A`
 
 It's unclear what format ZDNS expects input. Let's inventory the ways ZDNS expects input and document them.
 
At minimum:

- [ ] `--help` text
- [ ] README.md
