### ISSUE TITLE
MX records w/ preferences (and "exchanges" JSON label) disappeared?

### ISSUE THREAD

**Issue by brandonpoc** [zmap/zdns#37]
Output for the MX module used to include an "exchanges" category in JSON that contained the MX record with its MX priority and also an option "-ipv[4/6]-lookup" that would lookup the MX records A/AAAA records. Now, however, "zdns MX" does not provide any of this - instead it provides the MXes in the "answers" JSON field, with no MX priority/preference, and the "-ipv[4/6]-lookup" options are gone as well.

What happened here? It was working fine just a few compiles / pulls ago.

**Comment by brandonpoc** [comment]
Never mind - I see that the module is "MXLOOKUP". However, in the past, it worked with "MX" not "MXLOOKUP". When did this change, and why?

**Comment by zakird** [comment]
There's some more documentation in the README but essentially we split up
modules that report back the raw DNS responses and ones with additional
logic.
