### ISSUE TITLE
PTR module causes zDNS to exit if given bad IP address

### ISSUE THREAD

**Issue by brandonpoc** [zmap/zdns#53]
This logic, shown below, in the PTR module (modules/ptr/ptr.go) causes zdns to actually exit. I have zdns operating as part of an automated daily run that looks up millions of domains A records, and the PTR of those results, and I found that this was quite literally killing my processing efforts. I'd imagine most other users don't want this to exit if given a bad IP either. Wouldn't the proper, expected result be an error message such as {name: "bad IP address", status: "invalid ip error"} or something in JSON instead of it exiting? Considering that zdns can process gigantic files with great speed, having the program exit entirely because of a bad IP address is unwarranted.

Code is below:

```
    nameServer := s.Factory.Factory.RandomNameServer()
    name, err := dns.ReverseAddr(name)
    if err != nil {
            log.Fatal("Invalid IP address received:", name)
    }
```

**Comment by zakird** [comment]
This has been fixed by #55.
