### ISSUE TITLE
CLI option to silence the listing of nameservers

### ISSUE THREAD

**Issue by brandonpoc** [zmap/zdns#62]
Can we get an option to silence the output of the nameservers list when no nameservers are specified on the command line? I have a list of about 500 and it fills up the screen, obscuring whatever else I was doing.

**Comment by zakird** [comment]
This can be controlled by setting the log verbosity.

**Comment by brandonpoc** [comment]
What must verbosity be set to? I tried setting to the lowest and it still showed the nameservers;

~:# zdns MX -verbosity 1  
INFO[0000] no name servers specified. will use: 10.55.0.70:53, 10.55.0.71:53

Same with every -verbosity setting 1 - 5.

**Comment by brandonpoc** [comment]
Any idea? I set verbosity from 1 to 5 and got the same output. I also tried "0" (even though that is not listed as a valid verbosity setting) and got the same result.

**Comment by brandonpoc** [comment]
Hello,

Have you been able to resolve the verbosity question?

**Comment by brandonpoc** [comment]
There's nothing using the 'Verbosity' option at all, as there's no SetLevel() being assigend for the logrus 'log' class. I fixed this.

So, I did a simple fix for the DNS server "will use: <dns servers>" output and others. I have it interpreting the Verbosity flag and assigning the proper log level from the logrus package. For instance, verbosity 1 is log level ErrorLevel; verbosity 5 is log level DebugLevel (the higehst, most verbose).  In this way, now the log.InfoMsg () etc work as expected with the proper verbosity. Also default verbosity has been changed from 3 to 4 (InfoLevel).

You can merge it into the source tree, I am not familiar with git and "forking pushing pulling pull requests" all that fodder (I'm from the age of CVS for version control/changes and shared development over NFS and centralized development boxes with "screen" ;D) , but the diff -Nru patch is attached.

Thanks,

Brandon

[zdns.patch.txt](https://github.com/zmap/zdns/files/457991/zdns.patch.txt)

**Comment by zakird** [comment]
This was merged in 085964c2280001ececafb38e9a8f7db0f6ff2771.
