### ISSUE TITLE
Option to specify IP(s) from which we send queries

### ISSUE THREAD

**Issue by brandonpoc** [zmap/zdns#63]
I have three local cacheing-only resolvers running 'unbound' and each resolver has 16 IPs attached to it (as well as ~1024 IPv6 IPs), through which unbound rotates round-robin when sending outbound requests on behalf of lookups made from local clients.

It would be nice if zdns had an option to specify from which IP(s) it sends its requests from (that is, which IP it would bind() to). In a case where I have multiple IPs on a machine, this would allow me to kind of spread the load around when doing heavy NS lookups on public servers. It could be presented with a CLI option like -source-ips IP1,IP2,IP3 etc like you may specify name servers. The purpose of this is to help avoid banning on public DNS servers during heavy query sessions. And, considering zdns was built for this kind of thing (heavy queries!), I'd imagine an option like this is a natural progression and should not be too difficult implement (in C I just set the bind() for the socket; with Go, I have no idea).

Thanks

**Comment by zakird** [comment]
I agree that this would be potentially useful and fits the scope of ZDNS. However, given our workload, it's unlikely that the core team will have a chance to tackle this issue in the near future. if you have time to implement it, we'd be happy to accept a pull request.

**Comment by emremuratercan** [comment]
Hello zakird i have an issue something like your wish. Did you handled with your problem?

**Comment by zakird** [comment]
@stklcode fixed this in #173, which I merged with some additional commits.
