### ISSUE TITLE
[Bug] a-module sometimes outputs empty answer

### ISSUE THREAD

**Issue by aaspring** [zmap/zdns#70]
From the eakir744mcoetme2-alexa-top1m-www-alookups.20160907.json run. Note that object["answers"][0] is an empty object.

{
  "data": {
    "protocol": "udp",
    "authorities": [
      {
        "answer": "ns1.pr.gov.",
        "name": "pr.gov",
        "type": "NS",
        "ttl": 11711
      },
      {
        "answer": "ns2.pr.gov.",
        "name": "pr.gov",
        "type": "NS",
        "ttl": 11711
      }
    ],
    "additionals": [
      {
        "answer": "64.185.221.2",
        "name": "ns1.pr.gov",
        "type": "A",
        "ttl": 11711
      },
      {
        "answer": "64.185.205.211",
        "name": "ns2.pr.gov",
        "type": "A",
        "ttl": 11711
      }
    ],
    "answers": [
      {},
      {
        "answer": "www.pr.gov.",
        "name": "www.gobierno.pr",
        "type": "CNAME",
        "ttl": 55033
      },
      {
        "answer": "pr.gov.",
        "name": "www.pr.gov",
        "type": "CNAME",
        "ttl": 120
      },
      {
        "answer": "64.185.222.145",
        "name": "pr.gov",
        "type": "A",
        "ttl": 180
      }
    ]
  },
  "status": "NOERROR",
  "alexa_rank": 44972,
  "name": "gobierno.pr",
  "altered_name": "www.gobierno.pr"
}

**Comment by zakird** [comment]
The issue here looks like www. is running A instead of alookup in ZDNS. This has been fixed now.
