### ISSUE TITLE
DMARC Scan module should include a query against _dmarc.$DOMAIN.$TLD

### ISSUE THREAD

**Issue by openasocket** [zmap/zdns#76]
For ease of use by an end user using the DMARC Module should produce queries against TXT records for _dmarc.$DOMAIN.$TLD, as well as against the  $DOMAIN.$TLD as it currently does.   This is due to the fact that many DMARC service providers and documentation state to put all dmarc records under a subdomain of _dmarc, while other domains will put those TXT records at root. If the goal is to provide as wide of coverage as possible for scanning domains for DMARC records a simple prepending of _dmarc. to any domain to be scanned would produce more results.  

Ideal logic may be to query against _dmarc. and if nothing is found try against the domain.tld.  (there should be a higher incidence of results under _dmarc domains) 

By adding this change, users of the DMARC module would get more accurate scan results and would be saved the time of having to produce two lists of domains to run two scans against (one with prepend _dmarc. and the other with just the domain). 

Results of scanning against _dmarc.$DOMAIN:

{"name":"_dmarc.360.cn","alexa_rank":20,"status":"NXDOMAIN","data":{}}
{"name":"_dmarc.twitter.com","alexa_rank":10,"status":"NOERROR","data":{"dmarc":"v=DMARC1; p=reject; rua=mailto:d@rua.agari.com; ruf=mailto:d@ruf.agari.com; fo=1"}}
{"name":"_dmarc.pinterest.com","alexa_rank":44,"status":"NOERROR","data":{"dmarc":"v=DMARC1; p=reject; fo=1; pct=100; rua=mailto:pinterest@rua.agari.com,mailto:dmarc_agg@250ok.com; ruf=mailto:pinterest@ruf.agari.com,mailto:dmarc_fr@250ok.com"}}
{"name":"_dmarc.google.co.jp","alexa_rank":14,"status":"NOERROR","data":{"dmarc":"v=DMARC1; p=reject; rua=mailto:mailauth-reports@google.com"}}
{"name":"_dmarc.twitch.tv","alexa_rank":92,"status":"NOERROR","data":{"dmarc":"v=DMARC1; p=none; fo=1; ri=3600; rua=mailto:twitch@rua.agari.com; ruf=mailto:twitch@ruf.agari.com"}}
{"name":"_dmarc.netflix.com","alexa_rank":43,"status":"NOERROR","data":{"dmarc":"v=DMARC1;p=reject;pct=100;ruf=mailto:d@ruf.agari.com,mailto:netflix@ruf.netcraft.com;rua=mailto:d@rua.agari.com,mailto:netflix@rua.netcraft.com"}}
{"name":"_dmarc.google.com","alexa_rank":1,"status":"NOERROR","data":{"dmarc":"v=DMARC1; p=reject; rua=mailto:mailauth-reports@google.com"}}
{"name":"_dmarc.apple.com","alexa_rank":36,"status":"NOERROR","data":{"dmarc":"v=DMARC1;p=none;ruf=mailto:d@ruf.agari.com;rua=mailto:d@rua.agari.com;fo=1"}}
{"name":"_dmarc.himado.in","alexa_rank":818,"status":"NXDOMAIN","data":{}}
{"name":"_dmarc.google.co.kr","alexa_rank":61,"status":"NOERROR","data":{"dmarc":"v=DMARC1; p=reject; rua=mailto:mailauth-reports@google.com"}}
{"name":"_dmarc.instagram.com","alexa_rank":15,"status":"NOERROR","data":{"dmarc":"v=DMARC1; p=reject; rua=mailto:d@rua.agari.com; ruf=mailto:d@ruf.agari.com;"}}
{"name":"_dmarc.thewhizmarketing.com","alexa_rank":261,"status":"NXDOMAIN","data":{}}
{"name":"_dmarc.hao123.com","alexa_rank":19,"status":"NXDOMAIN","data":{}}
{"name":"_dmarc.weibo.com","alexa_rank":17,"status":"SERVFAIL","data":{}}
{"name":"_dmarc.google.com.vn","alexa_rank":183,"status":"NOERROR","data":{"dmarc":"v=DMARC1; p=reject; rua=mailto:mailauth-reports@google.com"}}
{"name":"_dmarc.bhphotovideo.com","alexa_rank":817,"status":"NXDOMAIN","data":{}}
{"name":"_dmarc.wikipedia.org","alexa_rank":6,"status":"NOERROR","data":{"dmarc":"v=DMARC1; p=none; sp=none; rua=mailto:dmarc-rua@wikimedia.org; ruf=mailto:dmarc-ruf@wikimedia.org;"}}
{"name":"_dmarc.amazon.com","alexa_rank":8,"status":"NOERROR","data":{"dmarc":"v=DMARC1; p=quarantine; pct=100; rua=mailto:dmarc-reports@bounces.amazon.com; ruf=mailto:dmarc-reports@bounces.amazon.com"}}
{"name":"_dmarc.outbrain.com","alexa_rank":94,"status":"NXDOMAIN","data":{}}
{"name":"_dmarc.wordpress.com","alexa_rank":35,"status":"NOERROR","data":{"dmarc":"v=DMARC1; p=quarantine; pct=50; rua=mailto:0bqp2jnw@ag.dmarcian.com; ruf=mailto:0bqp2jnw@fr.dmarcian.com;"}}
{"name":"_dmarc.fc2.com","alexa_rank":66,"status":"NXDOMAIN","data":{}}
{"name":"_dmarc.linkedin.com","alexa_rank":16,"status":"NOERROR","data":{"dmarc":"v=DMARC1; p=reject; rua=mailto:d@rua.agari.com,mailto:dmarc_agg@auth.returnpath.net; ruf=mailto:d@ruf.agari.com,mailto:dmarc_afrf@auth.returnpath.net; pct=100"}}
{"name":"_dmarc.yahoo.com","alexa_rank":5,"status":"NOERROR","data":{"dmarc":"v=DMARC1; p=reject; pct=100; rua=mailto:dmarc_y_rua@yahoo.com;"}}
{"name":"_dmarc.google.com.mx","alexa_rank":51,"status":"NOERROR","data":{"dmarc":"v=DMARC1; p=reject; rua=mailto:mailauth-reports@google.com"}}
{"name":"_dmarc.ebay.com","alexa_rank":33,"status":"NOERROR","data":{"dmarc":"v=DMARC1; p=none; rua=mailto:ebay@rua.agari.com,mailto:dmarc_agg@auth.returnpath.net; ruf=mailto:ebay@ruf.agari.com,mailto:dmarc_afrf@auth.returnpath.net; fo=1; rf=afrf; pct=100"}}

Results of "default scan behavior" of DMARC module:
{"name":"fbcdn.net","alexa_rank":210,"status":"NORECORD","data":{}}
{"name":"google.com","alexa_rank":1,"status":"NORECORD","data":{}}
{"name":"instagram.com","alexa_rank":15,"status":"NORECORD","data":{}}
{"name":"mercadolibre.com.ar","alexa_rank":496,"status":"NORECORD","data":{}}
{"name":"doubleclick.net","alexa_rank":140,"status":"NORECORD","data":{}}
{"name":"openload.co","alexa_rank":219,"status":"NORECORD","data":{}}
{"name":"amazon.com","alexa_rank":8,"status":"NORECORD","data":{}}
{"name":"abs-cbn.com","alexa_rank":463,"status":"NORECORD","data":{}}
{"name":"wittyfeed.com","alexa_rank":286,"status":"NORECORD","data":{}}
{"name":"google.hu","alexa_rank":377,"status":"NORECORD","data":{}}
{"name":"leagueoflegends.com","alexa_rank":542,"status":"NORECORD","data":{}}
{"name":"googleapis.com","alexa_rank":406,"status":"NORECORD","data":{}}
{"name":"yahoo.com","alexa_rank":5,"status":"NORECORD","data":{}}
{"name":"nametests.com","alexa_rank":295,"status":"NORECORD","data":{}}
{"name":"sabah.com.tr","alexa_rank":394,"status":"NORECORD","data":{}}
{"name":"extratorrent.cc","alexa_rank":185,"status":"NORECORD","data":{}}
{"name":"linkshrink.net","alexa_rank":809,"status":"NORECORD","data":{}}
{"name":"behance.net","alexa_rank":411,"status":"NORECORD","data":{}}
{"name":"google.ca","alexa_rank":62,"status":"NORECORD","data":{}}
{"name":"blogspot.com","alexa_rank":42,"status":"NORECORD","data":{}}
{"name":"ask.fm","alexa_rank":499,"status":"NORECORD","data":{}}
{"name":"bloomberg.com","alexa_rank":414,"status":"NORECORD","data":{}}
{"name":"blogspot.com.eg","alexa_rank":853,"status":"NORECORD","data":{}}
{"name":"youtube.com","alexa_rank":2,"status":"NORECORD","data":{}}
{"name":"spankbang.com","alexa_rank":474,"status":"NORECORD","data":{}}

**Comment by zakird** [comment]
Are there any domains that you know of that store a record at the root instead of at _dmarc.domain.tld? We can change the default behavior to do _dmarc.domain.tld given that this is what the RFC says. However, this is also already possible by just specifying `--prefix=_dmarc`
