### ISSUE TITLE
Change default timeout value

### ISSUE THREAD

**Issue by paul-pearce** [zmap/zdns#85]
Currently the default zdns timeout value is 10 seconds. The default BIND timeout value is also 10 seconds. This creates a situation where zdns frequently returns `TIMEOUT` a few milliseconds before BIND returns `SERVFAIL` (assuming default invocations of both).

Bumping this to 15 seconds seems reasonable.

**Comment by dadrian** [comment]
Why not 11 seconds?

**Comment by paul-pearce** [comment]
Sure. I was going for a value that seemed "normal" by human standards, since it doesn't actually matter. Assuming a properly configured upstream resolver (which is totally trivial, right @zakird?) 11s should behave the same as 15s, over a large number of queries.
