### ISSUE TITLE
DNS lookup

### ISSUE THREAD

**Issue by XuChen-14** [zmap/zdns#90]
I download some datasets from "https://www.censys.io/data", such as "80-http-get-alexa_top1mil".I find that the dataset includes "alexa-results.csv.lz4" and the website introduces "this dataset is composed of the DNS lookups for each domain on the Alexa Top Million".How can I get the data in "alexa-results.csv.lz4" with DNS lookups ? What is the command? thank you.

**Comment by zakird** [comment]
This doesn't sound like it's related to ZDNS. For Censys related questions, please send these to the Censys discussion group: https://groups.google.com/a/censys.io/forum/#!forum/discussion.
